<?php

declare(strict_types=1);

namespace gordon\pdowrapper\dsn;

use Stringable;
use ValueError;

/**
 * Base DSN class
 *
 * @package gordon\pdowrapper\dsn
 * @license https://www.apache.org/licenses/LICENSE-2.0
 * @todo PHPUnit can't mock readonly classes yet, update this class to be read-only if/when mocking them becomes possible
 */
abstract class DSN implements Stringable
{
    protected const ELEMENT_TEMPLATE = "%s=%s";

    /**
     * @param string $dsnString The DSN generated by the subclass constructor
     * @throws ValueError
     */
    public function __construct(private readonly string $dsnString)
    {
        if (empty ($dsnString)) {
            throw new ValueError("DSN cannot be empty");
        }
    }

    /**
     * Return the DSN
     *
     * @return string
     */
    public function __toString(): string
    {
        return $this->dsnString;
    }
}
