<?php

declare(strict_types=1);

namespace gordon\pdowrapper\dsn;

use Stringable;
use ValueError;

/**
 * Base DSN class
 *
 * @package gordon\pdowrapper\dsn
 * @license https://www.apache.org/licenses/LICENSE-2.0
 * @todo PHPUnit can't mock readonly classes yet, update this class to be read-only if/when mocking them becomes possible
 */
abstract class DSN implements Stringable
{
    protected const ELEMENT_TEMPLATE = "%s=%s";

    private const PORT_MIN = 1;

    private const PORT_MAX = 65535;

    /**
     * @param string $dsnString The DSN generated by the subclass constructor
     * @throws ValueError
     */
    public function __construct(private readonly string $dsnString)
    {
        if (empty ($dsnString)) {
            throw new ValueError("DSN cannot be empty");
        }
    }

    /**
     * Return the DSN
     *
     * @return string
     */
    public function __toString(): string
    {
        return $this->dsnString;
    }

    /**
     * Validate that the given IP port is in a valid range
     *
     * @param int|null $port
     * @return void
     * @throws ValueError
     */
    protected function validatePort(?int $port) {
        if (null !== $port && ($port < self::PORT_MIN || $port > self::PORT_MAX)) {
            throw new ValueError(sprintf("Port must have a value between %d and %d", self::PORT_MIN, self::PORT_MAX));
        }
    }

    /**
     * Build the DSN parameter string
     *
     * @param array<string, mixed> $params
     * @return string
     */
    protected function buildParamString(array $params): string
    {
        $paramStrings = [];

        foreach (array_filter($params) as $key => $val) {
            $paramStrings[] = sprintf(self::ELEMENT_TEMPLATE, $key, $val);
        }

        return implode(";", $paramStrings);
    }
}
